/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as EvolucionRouteImport } from './routes/evolucion'
import { Route as BaulRouteImport } from './routes/baul'
import { Route as IndexRouteImport } from './routes/index'

const EvolucionRoute = EvolucionRouteImport.update({
  id: '/evolucion',
  path: '/evolucion',
  getParentRoute: () => rootRouteImport,
} as any)
const BaulRoute = BaulRouteImport.update({
  id: '/baul',
  path: '/baul',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baul': typeof BaulRoute
  '/evolucion': typeof EvolucionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baul': typeof BaulRoute
  '/evolucion': typeof EvolucionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baul': typeof BaulRoute
  '/evolucion': typeof EvolucionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/baul' | '/evolucion'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/baul' | '/evolucion'
  id: '__root__' | '/' | '/baul' | '/evolucion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaulRoute: typeof BaulRoute
  EvolucionRoute: typeof EvolucionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/evolucion': {
      id: '/evolucion'
      path: '/evolucion'
      fullPath: '/evolucion'
      preLoaderRoute: typeof EvolucionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baul': {
      id: '/baul'
      path: '/baul'
      fullPath: '/baul'
      preLoaderRoute: typeof BaulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaulRoute: BaulRoute,
  EvolucionRoute: EvolucionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
