/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PlanificacionRouteImport } from './routes/planificacion'
import { Route as LoginRouteImport } from './routes/login'
import { Route as EvolucionRouteImport } from './routes/evolucion'
import { Route as BaulRouteImport } from './routes/baul'
import { Route as IndexRouteImport } from './routes/index'

const PlanificacionRoute = PlanificacionRouteImport.update({
  id: '/planificacion',
  path: '/planificacion',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const EvolucionRoute = EvolucionRouteImport.update({
  id: '/evolucion',
  path: '/evolucion',
  getParentRoute: () => rootRouteImport,
} as any)
const BaulRoute = BaulRouteImport.update({
  id: '/baul',
  path: '/baul',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/baul': typeof BaulRoute
  '/evolucion': typeof EvolucionRoute
  '/login': typeof LoginRoute
  '/planificacion': typeof PlanificacionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/baul': typeof BaulRoute
  '/evolucion': typeof EvolucionRoute
  '/login': typeof LoginRoute
  '/planificacion': typeof PlanificacionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/baul': typeof BaulRoute
  '/evolucion': typeof EvolucionRoute
  '/login': typeof LoginRoute
  '/planificacion': typeof PlanificacionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/baul' | '/evolucion' | '/login' | '/planificacion'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/baul' | '/evolucion' | '/login' | '/planificacion'
  id: '__root__' | '/' | '/baul' | '/evolucion' | '/login' | '/planificacion'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BaulRoute: typeof BaulRoute
  EvolucionRoute: typeof EvolucionRoute
  LoginRoute: typeof LoginRoute
  PlanificacionRoute: typeof PlanificacionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/planificacion': {
      id: '/planificacion'
      path: '/planificacion'
      fullPath: '/planificacion'
      preLoaderRoute: typeof PlanificacionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evolucion': {
      id: '/evolucion'
      path: '/evolucion'
      fullPath: '/evolucion'
      preLoaderRoute: typeof EvolucionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/baul': {
      id: '/baul'
      path: '/baul'
      fullPath: '/baul'
      preLoaderRoute: typeof BaulRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BaulRoute: BaulRoute,
  EvolucionRoute: EvolucionRoute,
  LoginRoute: LoginRoute,
  PlanificacionRoute: PlanificacionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
